### ISSUE TITLE
Extract the doc generation logic into a seperate package

### ISSUE THREAD

**Issue by yqrashawn** [Conflux-Chain/conflux-developer-site#12] opened 2020-04-10 04:32 UTC
# The current sidebar config generation behaviour
The `id` syntax in docusaurus v2 sidebar is like below
```
docs/introduction/en/what_is_conflux
```
`docs/introduction/en` is the directory contains the `what_is_conflux.md` doc file. `what_is_conflux` is the id of the [documentation](https://github.com/Conflux-Chain/conflux-developer-site/blob/6359fb163665ca5110359470ccb4d678c22694e5/docs/introduction/en/what_is_conflux.md#L2).

This needs users to actively maintain the `id` every time there's doc file location change. 

We made a hack [here](https://github.com/Conflux-Chain/conflux-developer-site/blob/6359fb163665ca5110359470ccb4d678c22694e5/development/gen_each_lang_sidebars_config.js#L1) to enable user just specify the folder in [docs dir](https://github.com/Conflux-Chain/conflux-developer-site/tree/master/docs/) and doc id so that we don't need user to maintain the location of the doc file, like below.
```js
{ type: "doc", folder: "conflux-portal", id: "introduction" }
```

Currently, the `yarn genconf` command runs the script and generates a `sidebars.en.js` with the docusaurus v2 syntax.

# The problem
This gen doc logic should go into [@docusaurus/plugin-content-docs](https://www.npmjs.com/package/@docusaurus/plugin-content-docs), which is used by [@docusaurus/preset-classic](https://www.npmjs.com/package/@docusaurus/preset-classic) and then this project.

# Recommended solution
Create our own docusaurus preset and custom everything(site design, gen config) in it.
Additionally, we need to add multi-language support and integrate it with the [soon coming i18n feature](https://v2.docusaurus.io/docs/introduction/#features).

# Summary
We need to 
1. fork docusaurus, create a custom preset
2. add the multi-language feature 
3. integrate official i18n support into it when the feature releases.

**Comment by angelia-yuqi-personal** [comment] 2020-04-10 04:41
I think maybe we can wait the official i18n support

**Comment by yqrashawn** [comment] 2020-04-10 04:58
It depends on how they are implementing the i18n feature. If it only supports the text on UI not the contents, we still need to implement the multi-language feature. 

Or we can do it like the [react community](https://github.com/reactjs?q=.reactjs.org&type=source&language=) with multiple sites.

**Comment by xiaods** [comment] 2020-04-10 07:54
hey, in the early stage, we suggest focusing on content management. if the site only supports English id, how about use English id to manage the Chinese docs. so it make sure works, then we can work in times. I prefer don't add more development resources to refactor the docs site generate feature. we can claim our feature and hear the Docusaurus community's suggestions.

**Comment by xiaods** [comment] 2020-04-10 07:55
I don't mind the English interface.

**Comment by angelia-yuqi-personal** [comment] 2020-04-11 04:01
> hey, in the early stage, we suggest focusing on content management. if the site only supports English id, how about use English id to manage the Chinese docs. so it make sure works, then we can work in times. I prefer don't add more development resources to refactor the docs site generate feature. we can claim our feature and hear the Docusaurus community's suggestions.

the problem is how to switch between the Chinese and English. If our goal is to supply the Chinese site， we can deploy different sites with two repos for like the [react community ](https://github.com/reactjs?q=.reactjs.org&type=source&language=) easily

**Comment by xiaods** [comment] 2020-04-11 12:09
@angelia-yuqi-personal docs team original requirement is support multi-language developer site. It will engage all another country's developers to involved.  if we can keep the repo is only the one, yes, I agree we can add another Chinese site to a special Chinese developer. if not, I want to mix all docs in one site, just use some category to list here.

**Comment by xiaods** [comment] 2020-04-12 04:37
FYI  Frank comments
2. 多语言版本是单站点还是多站点？我觉得单站点容易管理。 比如
[简体中文]docs/cn/conflux-portal/overview.md,docs/cn/conflux-portal/treegraph.md ...
[简体中文]docs/cn-hk/conflux-portal/overview.md,docs/cn-hk/conflux-portal/treegraph.md ...
[English]docs/en/conflux-portal/overview.md,docs/en/conflux-portal/treegraph.md ...
[Korean]docs/kr/conflux-portal/overview.md,docs/kr/conflux-portal/treegraph.md ...
你们当前写的hack代码也实现了这个功能。

3.多语言切换， 可以考虑用cookie 或者localstorage 客户端存储

你们可以先把英文先弄出来， 我们施工队负责把中文翻译出来，这些.md 文档应该不会受到i18n 发布的影响。

**Comment by chinajinwanjun** [comment] 2020-04-13 01:29
we can load all language sidebars with hide status, and then display the current selected language.

This need to inject some custom codes in docs file, I am working on it.

**Comment by yqrashawn** [comment] 2020-04-13 04:30
Need to tweak the original classic theme here
https://github.com/facebook/docusaurus/tree/master/packages/docusaurus-theme-classic/src/theme

**Comment by xiaods** [comment] 2020-04-30 03:58
done by core team.

**Comment by xiaods** [comment] 2020-05-10 07:17
@yqrashawn please close this issue.

**Closed** 2021-07-22 03:47 UTC
